source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target ‘Venues’ do
pod 'GoogleMaps'
pod 'GoogleMobileVision'
pod 'Alamofire'
pod 'Socket.IO-Client-Swift'
pod 'SwiftyJSON'
pod 'Apollo'
pod 'Stripe'
end
